export const data = {
  about:
    "I'm a full-stack developer from India, with a passion for building things and exploring new technologies creating functional and user-friendly web experiences. I love crafting visually appealing products that effectively convey your message and identity. My goal is to bring your ideas to life, ensuring they are efficient, aesthetically pleasing, and engaging. I'm here to turn your vision into reality.",
  education: [
    {
      img: '/gec-daman.png',
      clg: 'Government Engineering College, Daman',
      course: 'Bachelor of Engineering in Computer Engineering.',
      batch: '2022 - 2025',
    },
    {
      img: '/karad.png',
      clg: 'Dr. BBA Govt. Poly. Karad (D.P.), Silvassa',
      course: 'Diploma in Computer Engineering.',
      batch: '2019 - 2022',
    },
  ],
  skills: [
    'React',
    'Next.js',
    'HTML',
    'CSS',
    'Javascript',
    'Typescript',
    'Node.js',
    'Express.js',
    'MongoDB',
    'Tailwind CSS',
    'Shadcn',
    'Git',
    'Github',
    'PostgreSQL',
    'Prisma',
    'Docker',
    'AWS',
    'C++',
    'Core Java',
  ],
  projects: [
    {
      title: 'Resume Builder',
      desc: 'Developed a real-time resume builder using React, allowing users to create and edit resumes dynamically. Fully responsive design for optimal UX across devices. Integrated local storage to save user progress.',
      img: '/resume-builder.png',
      website: 'https://resume-builder-shubh.vercel.app/',
      code: 'https://github.com/shubhampatil1602/resume-builder',
      tech: ['React.js', 'Tailwind CSS', 'Shadcn', 'Aceternity UI'],
    },
    {
      title: 'Blogging Website',
      desc: 'Developed a blogging platform using Cloudflare Workers. Ensured type safety and data validation using TypeScript and Zod. Integrated PostgreSQL with Prisma for efficient data handling and management. Implemented secure authentication using JWT.',
      img: '/blogging.png',
      website: 'https://medium-blogging-xi.vercel.app/',
      code: 'https://github.com/shubhampatil1602/medium-blogging',
      tech: [
        'React.js',
        'Tailwind CSS',
        'Hono.js',
        'Prisma',
        'PostgreSQL',
        'Gemini AI',
        'TS',
      ],
    },
    {
      title: 'Food App',
      desc: 'Developed a frontend for a food delivery app, integrating the Swiggy API for real-time restaurant data. Implemented a config-driven (location-based UI) to display nearby restaurants and enhance personalized browsing. Built search functionality and add-to-cart features. Fully responsive.',
      img: '/swiggy.png',
      code: 'https://github.com/shubhampatil1602/swiggy-clone',
      tech: ['React.js', 'Tailwind CSS', 'Redux Toolkit'],
    },
    {
      title: 'Hoobank UI',
      desc: 'The HooBank UI is a fully responsive website built using React and Tailwind CSS, transforming a Figma design into clean, functional code. The site features a sleek, modern design with smooth interactions and adaptable layouts across devices.',
      img: '/hoobank.png',
      website: 'https://hoo-bank-ui-one.vercel.app/',
      code: 'https://github.com/shubhampatil1602/HooBank-ui',
      tech: ['React.js', 'Tailwind CSS'],
    },
  ],
  experiences: [
    {
      id: 1,
      img: '/infolabz.png',
      company: 'INFOLABZ IT SERVICES PVT LTD',
      role: 'React Developer Intern',
      duration: 'June 2024 - July 2024',
      desc: 'I completed an internship focused on React, where I worked on live API handling and data fetching. I also utilized Bootstrap and Tailwind CSS to develop small projects, enhancing my ability to create responsive and visually appealing user interfaces. This experience allowed me to apply my skills in a practical setting and deepened my passion for web development.',
    },
  ],
};
