export const data = {
  about:
    "I'm a full-stack developer from India, with a passion for building things and exploring new technologies creating functional and user-friendly web experiences. I love crafting visually appealing products that effectively convey your message and identity. My goal is to bring your ideas to life, ensuring they are efficient, aesthetically pleasing, and engaging.",
  education: [
    {
      img: "/gec-daman.png",
      clg: "Government Engineering College, Daman",
      course: "(B.E.) Bachelor of Engineering in Computer Engineering.",
      batch: "2022 - 2025",
    },
    {
      img: "/karad.png",
      clg: "Dr. BBA Govt. Poly. Karad (D.P.), Silvassa",
      course: "Diploma in Computer Engineering.",
      batch: "2019 - 2022",
    },
  ],
  skills: [
    "React",
    "Next.js",
    "HTML",
    "CSS",
    "Javascript",
    "Typescript",
    "Node.js",
    "Express.js",
    "MongoDB",
    "Tailwind CSS",
    "Shadcn",
    "Git",
    "Github",
    "PostgreSQL",
    "Prisma",
    "Docker",
    "AWS",
  ],
  projects: [
    {
      title: "Resume Builder",
      desc: "Developed a real-time resume builder using React, allowing users to create and edit resumes dynamically. Fully responsive design for optimal UX across devices. Integrated local storage to save user progress.",
      img: "/resume-builder.png",
      website: "https://resume-builder-shubh.vercel.app/",
      code: "https://github.com/shubhampatil1602/resume-builder",
      tech: ["React.js", "Tailwind CSS", "Shadcn", "Aceternity UI"],
    },
    {
      title: "SiuuTube",
      desc: "Developed a video streaming platform using the YouTube Live API. Optimized search suggestions with debouncing and caching in the Redux store. Integrated a shimmer effect for smooth UI transitions. Built an n-level nested comment section. Implemented live chat functionality, ensuring seamless performance without app freeze, even during high traffic. Fully responsive design across devices.",
      img: "/siuutube.png",
      code: "https://github.com/shubhampatil1602/SiuuTube",
      tech: ["React.js", "Tailwind CSS", "Redux Toolkit"],
    },
    {
      title: "Food App",
      desc: "Developed a frontend for a food delivery app, integrating the Swiggy API for real-time restaurant data. Implemented a config-driven (location-based UI) to display nearby restaurants and enhance personalized browsing. Built search functionality and add-to-cart features. Fully responsive.",
      img: "/swiggy.png",
      code: "https://github.com/shubhampatil1602/swiggy-clone",
      tech: ["React.js", "Tailwind CSS", "Redux Toolkit"],
    },
    {
      title: "Blogging Website",
      desc: "Developed a blogging platform using Cloudflare Workers. Ensured type safety and data validation using TypeScript and Zod. Integrated PostgreSQL with Prisma for efficient data handling and management. Implemented secure authentication using JWT.",
      img: "/blogging.png",
      website: "https://medium-blogging-xi.vercel.app/",
      code: "https://github.com/shubhampatil1602/medium-blogging",
      tech: [
        "React.js",
        "Tailwind CSS",
        "Hono.js",
        "Prisma",
        "PostgreSQL",
        "Gemini AI",
        "TS",
      ],
    },

    {
      title: "Hoobank UI",
      desc: "The HooBank UI is a fully responsive website built using React and Tailwind CSS, transforming a Figma design into clean, functional code. The site features a sleek, modern design with smooth interactions and adaptable layouts across devices.",
      img: "/hoobank.png",
      website: "https://hoo-bank-ui-one.vercel.app/",
      code: "https://github.com/shubhampatil1602/HooBank-ui",
      tech: ["React.js", "Tailwind CSS"],
    },
    {
      title: "Dotprolabs Moonex UI",
      desc: "The Moonex UI is a fully responsive website built using React and Tailwind CSS, transforming a Figma design into clean, functional code. The site features a sleek, modern design with smooth animations and adaptable layouts across devices.",
      img: "/moonex.png",
      website: "https://dotprolabs-moonex-ui-shubh.vercel.app/",
      code: "https://github.com/shubhampatil1602/dotprolabs-moonex-ui",
      tech: ["React.js", "Tailwind CSS"],
    },
  ],
  experiences: [
    {
      id: "ajdbc5678",
      img: "https://phicsit.in/wp-content/uploads/2023/12/phy.png",
      company: "PHICSIT InfoTech Pvt. Ltd.",
      role: "Frontend Developer Intern",
      duration: "Nov. 2024 - Present",
      desc: "Created pages like create-quiz, explore and more using React.js. Built interactive modals, improved responsive UI/UX designs, and resolved bugs. Collaborated using Git, managing branches efficiently to streamline development.",
    },
    {
      id: "qyWD67235",
      img: "/infolabz.png",
      company: "INFOLABZ IT SERVICES PVT LTD",
      role: "React Developer Intern",
      duration: "June 2024 - July 2024",
      desc: "I completed an internship focused on React, where I worked on live API handling and data fetching. I also utilized Bootstrap and Tailwind CSS to develop small projects, enhancing my ability to create responsive and visually appealing user interfaces.",
    },
  ],
};
